---
- name: restart zookeeper
  service: name=zookeeper state=restarted
  sudo: yes
  when: not (is_integration_test is defined and is_integration_test and
      (ansible_os_family == "RedHat" or ansible_distribution == "CentOS"))
